#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor VGA-1 -d I III V VII IX
bspc monitor LVDS-1 -d II IV VI VIII X

bspc config border_width                  1
bspc config bottom_padding                1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom &
polybar &
feh --bg-scale ~/Pictures/Wallpapers/tokyo.png
/home/adrien/.config/conky/Auva/start.sh
